 function paneer(){
    console.log('paneer lene jana h')
}
function mummy(callback){
    callback()
  console.log('paneer ki sbji bnana h')} // CALLBACK PARAMETR
mummy(paneer) // PANEER ARGUEMENT
// CALLBACK EK AISA FNCN HOTA H JO KISI OR FNCN KE ANDR ARGUEMENT KI TRH PASS HOTA .
// HIGHER ORDER FNCN EK AISA FNCN HOTA H JISKE ANDR KOI OR FNCN AS A ARGUEMENT PASS HOTA H .
// PARAMETER EK AISA VARIABLE H  HIGHER ORDER FNCN KE ANDR JO VALUE STORE KREGA JO ARGUEMENT VARIABLE KE FORM ME PASS KI JGH CALLABACK FNCN KE ANDR .
// Parameter: The variable name in the function's definition. It acts as a placeholder for a value .
// Argument: The actual value that is passed to the function when it is invoked (called) .
// LEXICAL SCOPE: VO SCOPE JISME US FNCN KA INTERNAL SCOPE + PARENT FNCN KA SCOPE (IT COULD BE GLOBAL SCOPE AS WELL JUST DEPEND UPON KI FNCN KAHA DEFINE KIYA GYA H) .
// KISI FNCN KE ANDAR AGR HUM KISI BHI VARIABLE KO CALL KRNGE TO PHLE VO APNE SCOPE ME DHUNDHEGA FIR AGR NI VHA TO APNE PARENT KE SCOPE ME DHUNDHEGA .
function sum(){
    let x=20;
    return x;
}
let newvalue=sum()
console.log(newvalue)

// let newvalue=sum
// console.log(newvalue)

// AGR KISI FNCN ME RETURN NI USE KRENGE TO UNDEFINED DATATYPE AYEGA .
// AGR HUM FNCN KE AGE() USE KREGE TO FNCN KO CALL KRKE VALUE PRINT KRKE DEGA . 
// AGR HUM DIRECTLY FNCN KA NAAM LIKH DENGE TO PURA FNCN PRINT KR DEGA .
// AGR KOI VARIABLE KISI FNCN KE ANDR H TO VO USI FNCN KE SCOPE ME REH KR KAAM KREGA ,US FNCN KE BHR CALL KIYE JANE PR KAAM NI KREGA .
// CLOSURE:JS KE ANDR FNCN CREATE KRTE H TO FNCN APNE SATH KE CONTAINER/BUCKET CREATE KRTA H JISME VO APNE USED VARIABLES KO STORE KR LETA H , OR APNE PARENT KE VARIABLES KO STORE KR LEGA BUT SIRF VO WALE JO USE HOGE CHILD FNCN/CALLBACK FNCN ME USE HOGE .
// ARRAY: EK AISA KEYWORD/VARIABLE JO KI ALG ALG TYPE KE DATATYPES KO AS A INPUT ALLOW KRTA H .
// INDEXING: FOR ACCESSING ANY PARTICULAR POSITION WALI VALUE FROM AN ARRAY .

let array = [1,8,3,0,9]
array.push(10)
// ADDITION OF VALUE FROM BACK .
array.pop(9)
// REMOVAL OF VALUE FROM BACK .
array.unshift(12)
// ADDITION OF VALUE FROM STARTING .
array.shift(1)
// REMOVAL OF VALUE FROM END .
array.sort()
// TO SORT THE ARRAY IN AN ASCENDING ORDER .
array.reverse()
// USED TO REVERSE THE GIVEN ORDER OF THE ARRAY .
array.sort()
array.reverse()
// THESE TWO METHODS ARE USED RESPECTIVELY TO SORT THE ORDER IN DECREASING ORDER .
console.log(array)
for(let i = 0;i<array.length;i++){
  console.log(array[i])
}
// USED TO PRINT ARRAY IN THE ORDER ON WHICH INDEXING IS DONE .
let array1 = [1,8,3,0,9]
function add(element){
  return element+10
}
let newarray = array.map(function add(element) {return element+10} ) 
console.log(newarray)
// MAP : ADDS SOME FUNCN JO KI USKE ARGUEMENT ME DIYA JAYEGA AND FIR USKO ADD KREGA IN ALL EXISTING ELEMENTS OF AN ARRAY AND ACCUMELATES IT INTO A NEW ARRAY

let array2 = [2,4,5,9,1]
// FILTER : EXISTING ARRAY ELEMENTS PR EK FUNCN APPLY KRTA H JISME KOI CONDN HOTI H FIR VALUE RETURN KRTA H AFTER THE FILTERATION PROCESS INTO A NEW ARRAY
function filterelement(element){
  return(element%2==0)
}
let newarray3 = array.filter(filterelement)
// FILTER : ISKE ARGUEMENT JO BHI FNCN PASS KROGE VO AS A CONDN PURANI ARRAY KE ELEMENTS ME PASS KRKE EK NAYE ME ACCUMELATE KR LEGA

let array6 = [1,2,3,4,5]
function total(acc,crr){
  return acc+crr
}

let x = array6.reduce(total,0)
console.log(x)
// REDUCE : 






